service: serverless-aws
frameworkVersion: '2'

provider:
  name: aws
  runtime: java11
  lambdaHashingVersion: 20201221

package:
  artifact: target/serverless-aws-dev.jar

functions:
  hello:
    handler: com.goapigo.Handler
    timeout: 30
    events:
      - httpApi:
          path: /repositories
          method: get
